<?php
$z[0]=Array("arclist","\r\n                            <a href=\"#\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a>\r\n                            ",463,658);
$z[0][4]['typeid']="26";
$z[0][4]['limit']="0,5";
$z[1]=Array("arclist","\r\n                            <a href=\"#\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a>\r\n                            ",951,1146);
$z[1][4]['typeid']="26";
$z[1][4]['limit']="5,5";

?>