<?php
$z[0]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",153,259);
$z[0][4]['typeid']="1";
$z[1]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",379,485);
$z[1][4]['typeid']="4";
$z[2]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",584,691);
$z[2][4]['typeid']="11";
$z[3]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",780,887);
$z[3][4]['typeid']="16";
$z[4]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",983,1090);
$z[4][4]['typeid']="22";
$z[5]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",1193,1294);
$z[5][4]['typeid']="25";
$z[6]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",1310,1417);
$z[6][4]['typeid']="25";
$z[7]=Array("arclist","\r\n                            <li>\r\n                    	        <span>[field:global.autoindex/].</span>\r\n                                <div class=\"fEMain\">\r\n                        	        <strong><a href=\"[field:arcurl/]\" target=\"_blank\">[field:fulltitle/]</a></strong>\r\n                                    <p>[field:info function=\"cn_substr(@me,80)\"/]...</p>\r\n                                </div>\r\n                                <div class=\"clear\"></div>\r\n                            </li>\r\n                            ",1791,2368);
$z[7][4]['typeid']="28";
$z[7][4]['row']="6";

?>