<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",329,359);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",396,423);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1468,1505);
$z[3][4]['filename']="header.htm";
$z[4]=Array("arclist","\r\n                            <div class=\"box\">\r\n                                <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                                    <strong>[field:title/]</strong>\r\n                                    <p>[field:info function=\"cn_substr(@me,80)\"/]...</p>\r\n                                </a>\r\n                            </div>",3475,3872);
$z[4][4]['typeid']="27";
$z[5]=Array("arclist","\r\n            	<div class=\"iPNTop\">\r\n                	<div class=\"iPNTPic\">\r\n                    	<img src=\"[field:litpic/]\" />\r\n                    </div>\r\n                    <div class=\"iPNPicCont\">\r\n                    	<strong><a href=\"[field:arcurl/]\" target=\"_blank\">[field:fulltitle/]</a></strong>\r\n                        <p>\r\n[field:description/]</p>\r\n                    </div>\r\n                    <div class=\"clear\"></div>\r\n                </div>",5350,5876);
$z[5][4]['typeid']="22";
$z[5][4]['limit']="0,1";
$z[5][4]['type']=".image";
$z[6]=Array("arclist","\r\n                            <li>\r\n                                <a href=\"[field:arcurl/]\" target=\"_blank\">[field:fulltitle/]</a>\r\n                            </li>",5931,6151);
$z[6][4]['typeid']="22";
$z[6][4]['limit']="1,5";
$z[7]=Array("arclist","\r\n                            <li>\r\n                    	        <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                        	        <img src=\"[field:litpic/]\" />\r\n                                    <p>[field:title/]</p>\r\n                                </a>\r\n                            </li>",6531,6882);
$z[7][4]['typeid']="4";
$z[7][4]['row']="2";
$z[8]=Array("include","",7150,7183);
$z[8][4]['filename']="bo.htm";
$z[9]=Array("include","",7240,7278);
$z[9][4]['filename']="footer1.htm";
$z[10]=Array("include","",7282,7319);
$z[10][4]['filename']="footer.htm";

?>