<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",351,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,464);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1468,1503);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1787,1816);
$z[5][4]['name']="position";
$z[6]=Array("field","",1950,1971);
$z[6][4]['name']="content";
$z[7]=Array("channel","\r\n                            <li><a href=\"[field:typelink/]\" class=\"active\">[field:typename/]</a></li>\r\n                        ",2189,2429);
$z[7][4]['type']="son";
$z[7][4]['typeid']="1";
$z[7][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a> </li>";
$z[8]=Array("include","",3192,3225);
$z[8][4]['filename']="bo.htm";
$z[9]=Array("include","",3282,3320);
$z[9][4]['filename']="footer1.htm";
$z[10]=Array("include","",3324,3361);
$z[10][4]['filename']="footer.htm";

?>